# fly.toml app configuration file generated for remix-docs-ja on 2024-06-11T22:47:11+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remix-docs-ja'
primary_region = 'nrt'

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[http_services.machine_checks]
  image = "curlimages/curl"
  entrypoint = ["/bin/sh", "-c"]
  command = ["curl", "$FLY_TEST_MACHINE_IP", "|", "grep", "Remix"]
  kill_signal = "SIGKILL"
  kill_timeout = "5s"


[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
