packages:
  - ./apps/*
  - ./packages/*
catalog:
  '@ai-sdk/google': 1.2.18
  '@biomejs/biome': 1.9.4
  '@conform-to/react': 1.6.0
  '@conform-to/zod': 1.6.0
  '@mdx-js/rollup': 3.1.0
  '@prisma/client': 6.8.2
  '@radix-ui/react-accordion': 1.2.11
  '@radix-ui/react-alert-dialog': 1.1.14
  '@radix-ui/react-avatar': 1.1.10
  '@radix-ui/react-checkbox': 1.3.2
  '@radix-ui/react-collapsible': 1.1.11
  '@radix-ui/react-dialog': 1.1.14
  '@radix-ui/react-dropdown-menu': 2.1.15
  '@radix-ui/react-icons': 1.3.2
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-popover': 1.1.14
  '@radix-ui/react-progress': 1.1.7
  '@radix-ui/react-radio-group': 1.3.7
  '@radix-ui/react-select': 2.2.5
  '@radix-ui/react-separator': 1.1.7
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-switch': 1.2.5
  '@radix-ui/react-tabs': 1.1.12
  '@radix-ui/react-toggle': 1.1.9
  '@radix-ui/react-toggle-group': 1.1.10
  '@radix-ui/react-tooltip': 1.2.7
  '@react-router/dev': 7.6.1
  '@react-router/fs-routes': 7.6.1
  '@react-router/node': 7.6.1
  '@react-router/remix-routes-option-adapter': 7.6.1
  '@react-router/serve': 7.6.1
  '@rehype-pretty/transformers': 0.13.2
  '@shikijs/transformers': 3.4.2
  '@tailwindcss/typography': 0.5.16
  '@tailwindcss/vite': 4.1.7
  '@types/debug': 4.1.12
  '@types/hast': 3.0.4
  '@types/mdast': 4.0.4
  '@types/kuromoji': 0.1.3
  '@types/node': 22.15.23
  '@types/nprogress': 0.2.3
  '@types/react': 19.1.6
  '@types/react-dom': 19.1.5
  '@types/unist': 3.0.3
  '@vercel/og': 0.6.8
  ai: 4.3.16
  autoprefixer: 10.4.20
  cheerio: 1.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dayjs: 1.11.13
  debug: 4.4.1
  fast-glob: 3.3.3
  front-matter: 4.0.2
  gray-matter: 4.0.3
  hast: 1.0.0
  hast-util-from-html: 2.0.3
  hast-util-to-html: 9.0.5
  isbot: 5.1.28
  kuromoji: 0.1.2
  lucide-react: 0.511.0
  mdast: 3.0.0
  neverthrow: 8.2.0
  next-themes: 0.4.6
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  pagefind: 1.3.0
  postcss: 8.5.3
  prettier: 3.5.3
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-tailwindcss: 0.6.11
  prisma: 6.8.2
  react: 19.1.0
  react-dom: 19.1.0
  react-markdown: 10.1.0
  react-router: 7.6.1
  react-twc: 1.4.2
  rehype: 13.0.2
  rehype-autolink-headings: 7.1.0
  rehype-pretty-code: 0.14.1
  rehype-raw: 7.0.0
  rehype-slug: 6.0.0
  rehype-stringify: 10.0.1
  remark: 15.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-mdx-frontmatter: 5.1.0
  remark-parse: 11.0.0
  remark-rehype: 11.1.2
  remark-stringify: 11.0.0
  remix-flat-routes: 0.8.5
  remix-toast: 3.1.0
  shiki: 2.1.0
  sonner: 2.0.3
  tailwind-merge: 3.3.0
  tailwindcss: 4.1.7
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.7.1
  tsx: 4.19.4
  turbo: 2.5.3
  typescript: 5.8.3
  unified: 11.0.5
  unist: 0.0.1
  unist-util-visit: 5.0.0
  vite: 6.3.5
  vite-tsconfig-paths: 5.1.4
  vitest: 3.1.4
  wrangler: 4.17.0
  zod: 3.25.32
  zodix: 0.4.4
  radix-ui: 1.4.2
