packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@ai-sdk/google': 3.0.6
  '@biomejs/biome': 2.3.11
  '@coji/zodix': 0.7.0
  '@conform-to/react': 1.15.1
  '@conform-to/zod': 1.15.1
  '@mdx-js/rollup': 3.1.1
  '@react-router/dev': 7.12.0
  '@react-router/fs-routes': 7.12.0
  '@react-router/node': 7.12.0
  '@react-router/remix-routes-option-adapter': 7.12.0
  '@react-router/serve': 7.12.0
  '@rehype-pretty/transformers': 0.13.2
  '@shikijs/transformers': 3.21.0
  '@tailwindcss/typography': 0.5.19
  '@tailwindcss/vite': 4.1.18
  '@types/debug': 4.1.12
  '@types/hast': 3.0.4
  '@types/kuromoji': 0.1.3
  '@types/mdast': 4.0.4
  '@types/node': 25.0.6
  '@types/nprogress': 0.2.3
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  '@types/unist': 3.0.3
  '@vercel/og': 0.8.6
  ai: 6.0.27
  autoprefixer: 10.4.20
  cheerio: 1.1.2
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dayjs: 1.11.19
  debug: 4.4.3
  fast-glob: 3.3.3
  front-matter: 4.0.2
  gray-matter: 4.0.3
  hast: 1.0.0
  hast-util-from-html: 2.0.3
  hast-util-to-html: 9.0.5
  isbot: 5.1.32
  kuromoji: 0.1.2
  lucide-react: 0.562.0
  mdast: 3.0.0
  neverthrow: 8.2.0
  next-themes: 0.4.6
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  pagefind: 1.4.0
  postcss: 8.5.3
  prettier: 3.7.4
  prettier-plugin-organize-imports: 4.3.0
  prettier-plugin-tailwindcss: 0.7.2
  radix-ui: 1.4.3
  react: 19.2.3
  react-dom: 19.2.3
  react-markdown: 10.1.0
  react-router: 7.12.0
  react-twc: 1.5.1
  rehype: 13.0.2
  rehype-autolink-headings: 7.1.0
  rehype-pretty-code: 0.14.1
  rehype-raw: 7.0.0
  rehype-slug: 6.0.0
  rehype-stringify: 10.0.1
  remark: 15.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-mdx-frontmatter: 5.2.0
  remark-parse: 11.0.0
  remark-rehype: 11.1.2
  remark-stringify: 11.0.0
  remix-flat-routes: 0.8.5
  remix-toast: 4.0.0
  shiki: 2.1.0
  sonner: 2.0.7
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.9.0
  tsx: 4.21.0
  turbo: 2.7.3
  typescript: 5.9.3
  unified: 11.0.5
  unist: 0.0.1
  unist-util-visit: 5.0.0
  vite: 7.3.1
  vite-tsconfig-paths: 6.0.4
  vitest: 4.0.16
  wrangler: 4.58.0
  zod: 4.3.5
