packages:
  - ./apps/*
  - ./packages/*
catalog:
  '@biomejs/biome': 1.9.4
  '@mdx-js/rollup': 3.1.0
  '@radix-ui/react-accordion': 1.2.8
  '@radix-ui/react-avatar': 1.1.7
  '@radix-ui/react-collapsible': 1.1.8
  '@radix-ui/react-dialog': 1.1.8
  '@radix-ui/react-dropdown-menu': 2.1.12
  '@radix-ui/react-label': 2.1.4
  '@radix-ui/react-slot': 1.2.0
  '@react-router/dev': 7.5.2
  '@react-router/fs-routes': 7.5.2
  '@react-router/node': 7.5.2
  '@react-router/serve': 7.5.2
  '@rehype-pretty/transformers': 0.13.2
  '@shikijs/transformers': 3.3.0
  '@tailwindcss/typography': 0.5.16
  '@tailwindcss/vite': 4.1.4
  '@types/node': 22.15.2
  '@types/nprogress': 0.2.3
  '@types/react': 19.1.2
  '@types/react-dom': 19.1.2
  '@types/unist': 3.0.3
  '@vercel/og': 0.6.8
  autoprefixer: 10.4.20
  cheerio: 1.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  fast-glob: 3.3.3
  front-matter: 4.0.2
  gray-matter: 4.0.3
  isbot: 5.1.27
  lucide-react: 0.503.0
  next-themes: 0.4.6
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  pagefind: 1.3.0
  prettier: 3.5.3
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-tailwindcss: 0.6.11
  react: 19.1.0
  react-dom: 19.1.0
  react-markdown: 10.1.0
  react-router: 7.5.2
  react-twc: 1.4.2
  rehype: 13.0.2
  rehype-autolink-headings: 7.1.0
  rehype-pretty-code: 0.14.1
  rehype-raw: 7.0.0
  rehype-slug: 6.0.0
  rehype-stringify: 10.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.1
  remark-mdx-frontmatter: 5.1.0
  remark-parse: 11.0.0
  remark-rehype: 11.1.2
  shiki: 2.1.0
  tailwind-merge: 3.2.0
  tailwindcss: 4.1.4
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.7.0
  tsx: 4.19.3
  turbo: 2.5.2
  typescript: 5.8.3
  unified: 11.0.5
  unist: 0.0.1
  unist-util-visit: 5.0.0
  vite: 6.3.3
  vite-tsconfig-paths: 5.1.4
  vitest: 3.1.2
  wrangler: 4.13.2
