packages:
  - ./apps/*
  - ./packages/*
catalog:
  '@biomejs/biome': 1.9.4
  '@cloudflare/workers-types': 4.20241224.0
  '@mdx-js/rollup': 3.1.0
  '@radix-ui/react-accordion': 1.2.2
  '@radix-ui/react-avatar': 1.1.2
  '@radix-ui/react-dialog': 1.1.4
  '@radix-ui/react-dropdown-menu': 2.1.4
  '@radix-ui/react-label': 2.1.1
  '@radix-ui/react-slot': 1.1.1
  '@react-router/dev': 7.1.1
  '@react-router/fs-routes': 7.1.1
  '@react-router/node': 7.1.1
  '@react-router/serve': 7.1.1
  '@rehype-pretty/transformers': 0.13.2
  '@shikijs/transformers': 1.24.4
  '@tailwindcss/typography': 0.5.15
  '@types/nprogress': 0.2.3
  '@types/react': 19.0.2
  '@types/react-dom': 19.0.2
  '@types/unist': 3.0.3
  '@vercel/og': 0.6.4
  autoprefixer: 10.4.20
  cheerio: 1.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  fast-glob: 3.3.2
  front-matter: 4.0.2
  gray-matter: 4.0.3
  isbot: 5.1.19
  lucide-react: 0.469.0
  next-themes: 0.4.4
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  pagefind: 1.3.0
  postcss: 8.4.49
  prettier: 3.4.2
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-tailwindcss: 0.6.9
  react: 19.0.0
  react-dom: 19.0.0
  react-markdown: 9.0.1
  react-router: 7.1.1
  react-twc: 1.4.2
  rehype: 13.0.2
  rehype-autolink-headings: 7.1.0
  rehype-pretty-code: 0.14.0
  rehype-raw: 7.0.0
  rehype-slug: 6.0.0
  rehype-stringify: 10.0.1
  remark-frontmatter: 5.0.0
  remark-gfm: 4.0.0
  remark-mdx-frontmatter: 5.0.0
  remark-parse: 11.0.0
  remark-rehype: 11.1.1
  shiki: 1.24.4
  tailwind-merge: 2.6.0
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  ts-pattern: 5.6.0
  tsx: 4.19.2
  turbo: 2.3.3
  typescript: 5.7.2
  unified: 11.0.5
  unist: 0.0.1
  unist-util-visit: 5.0.0
  vite: 6.0.6
  vite-tsconfig-paths: 5.1.4
  vitest: 2.1.8
  wrangler: 3.99.0
