#:schema node_modules/wrangler/config-schema.json
name = "react-router-docs-ja"

main = "./server.ts"
workers_dev = true
account_id = "91ff95bcb91fbfa1b1c5c356262b1fe4"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-26"

# https://developers.cloudflare.com/workers/static-assets/binding/
assets = { directory = "./build/client", binding = 'ASSETS'}

[observability]
enabled = true

[build]
command = "pnpm run build"
